# http://jekyllrb.com/docs/configuration/

# Do not use tabs in configuration files
# This will either lead to parsing errors, or Jekyll will revert to the default settings. Use spaces instead.

# True para ligar Disqus, Analytics, etc.
production: false
# production: true

# Glob recursivo: assets/**/*.js
# https://github.com/mojombo/jekyll/issues/906
# exclude:
#   - _posts
#   - blog
#   - viagem

name: Aurelio.net
url: http://aurelio.net
description: 'Relaxe, leia com calma, aproveite a viagem.'

### permalink
# A configuração de permalink aqui vale somente para posts.
# Você pode usá-la no YAML de páginas individuais também.
#
# /blog/2009/04/29/slap-chop/index.html
permalink: /blog/:year/:month/:day/:title/
# permalink: /:title

### relative_permalinks
# Vale para a diretiva 'permalink' dentro do YAML de páginas.
relative_permalinks: false

# Used by category-pages plugin
category_dir: blog/category

### Syntax Highlight
pygments: true

### Markdown
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks"]
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]


### Page config (to insert in Front Matter)
# hide_author: true
# hide_date: true
# hide_read_more: true
# hide_share: true
# hide_comments: true
# hide_ads: true

# Use a pasta _data para guardar arquivos de dados
# If there's a file members.yml under the directory, then you can access contents of the file through site.data.members.
