# No tabs, use spaces only.
# Restart Jekyll --watch after editing here.

# True to turn on Disqus, Analytics, etc.
production: true

# Save the final HTMLs here
destination: ../aurelio.net.html

name: Aurelio.net
url: http://aurelio.net
description: 'Relaxe, leia com calma, aproveite a viagem.'

### permalink
# This config is valid for posts only.
# But you can use it in individual pages YAML.
#
# /blog/2009/04/29/slap-chop/index.html
permalink: /blog/:year/:month/:day/:title/
# permalink: /:title

### Syntax Highlight
highlighter: rouge  # Default since Jekyll 3.0

### Markdown
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "autolink"]
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

# Recursive glob: assets/**/*.js
# https://github.com/mojombo/jekyll/issues/906
exclude:
  - articles/README.md
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

defaults:
  -
    scope:
      path: ""  # all files in the project
    values:
      layout: "2014"
      author: aurelio
  -
    scope:
      path: "curso"
    values:
      title_prefix: "Evento: "
      hide_ads: true
      hide_date: true
      hide_tags: true
      hide_share: true
  -
    scope:
      path: "regex"
    values:
      css_extra: /regex/regex.css
      article_footer_after: regex-footer.html
      hide_ads: true
      hide_read_more: true
  -
    scope:
      path: "shell"
    values:
      css_extra: /regex/regex.css
      article_footer_after: shell-learn-more.html
      hide_ads: true
      hide_read_more: true

### Page config (to insert in Front Matter)
# published: false   # means: ignore this file
# title_prefix: "Foo: "
# css_extra: foo.css
# article_footer_after: include-file.html
# hide_title_suffix: true
# hide_heading: true
# hide_prev_next: true
# hide_byline: true
# hide_author: true
# hide_date: true
# hide_ads: true
# hide_ad_top: true
# hide_tags: true
# hide_read_more: true
# hide_share: true
# hide_comments: true

# Use _data folder to store data files
# If there's a file members.yml under the directory, then you can access contents of the file through site.data.members.
