#!/bin/bash
# add ads to every index.html

#echo 2006-04/26/index.html | while read file; do
find . -type f -name index.html | grep ^..200 | while read file; do
	if grep -qsr 'Praia de Matinhos' $file; then
		echo "Ads já colocados em $file"
		continue
	fi
	cp $file $file.tmp
	sed -e "
s|<title>$|&Fotos de Surf (de dentro d'\&aacute;gua) -|" -e '
s|<h2 align="center">$|&Praia de Matinhos,|

/<div class="body">/a \
<h1 align="center">Fotos de Surf (Aqu&aacute;ticas)</h1>

/<\/h2>/a \ 
\
<!--Begin Google Ads - Leaderboard-->\
<div class="googleadfaixa" style="text-align:center;margin:0em auto;">\
<script type="text/javascript"><!--\
google_ad_client ="pub-0009608813278754";\
google_alternate_color ="ffffff";\
google_ad_width = 728;\
google_ad_height = 90;\
google_ad_format ="728x90_as";\
google_ad_type ="text";\
google_ad_channel ="";\
google_color_border ="FFFFFF";\
google_color_bg ="FFFFFF";\
google_color_link ="0077ff";\
google_color_text ="333333";\
google_color_url ="333333";\
//--></script>\
<script type="text/javascript"\
  src="https://pagead2.googlesyndication.com/pagead/show_ads.js">\
</script>\
</div><!--googleadfaixa-->\
' $file.tmp > $file
rm $file.tmp
echo feito $file
done
