#!/bin/bash
# Build all txt2tags pages using the kiwi theme

# Make sure we are at the repository root
cd $(dirname "$0")
cd ..

# build it
git grep -l 'include/kiwi/config.t2t' |
    grep -v '^_scripts/' |
    xargs -n 1 _scripts/txt2tags-2.6.1102
