#!/bin/bash
# Build all txt2tags pages using the 10anos theme

# Make sure we are at the repository root
cd $(dirname "$0")
cd ..

detected_files=$(
    git grep -l 'include/10anos/config.t2t' |

    # skip false positives
    grep -v '^_scripts/' |
    grep -v '^shell/dialog/index-v6.t2t' |
    grep -v '^moneylog/'  # handled by build-moneylog
)

# build it
echo "$detected_files" |
    grep . |
    while read file
    do
        # echo "Will process $file"  # debug
        _scripts/txt2tags-2.6.1102 "$file"
    done
