#!/bin/bash
# Build all txt2tags pages using the 10anos theme

# Make sure we are at the repository root
cd $(dirname "$0")
cd ..

# build it
git grep -l 'include/10anos/config.t2t' |

    # skip false positives
    grep -v '^_scripts/' |
    grep -v '^shell/dialog/index-v6.t2t' |
    grep -v '^moneylog/_config.t2t' |

    # skip those who need custom conversion
    grep -v '^shell/canivete/canivete.conf'

    xargs -n 1 _scripts/txt2tags-2.6.1102

# build the extra pages
_scripts/txt2tags-2.6.1102 shell/canivete/es/index.t2t
_scripts/txt2tags-2.6.1102 shell/canivete/index.t2t
