#!/bin/bash
# Check for errors on the generated site

error() {
    echo
    echo "**** FAILED :("
    echo
    echo "$*" | head -n 40
    exit 1
}
cgrep() {
    grep --color=always "$@"
}

# Make sure we are at the repository root
cd $(dirname "$0")
cd ..

repo_root="$PWD"
site_root="$repo_root/_site"
files=$(_scripts/list-site-text-files)

# Search for the {{...}} pattern in repo files
check_accidental_liquid_markup() {

    # This check runs at the repo root
    cd "$repo_root" && git grep -I '{{.*}}' |

        # Remove false positives
        grep -v '^_includes/' |
        grep -v '^_layouts/' |
        grep -v '^_plugins/' |
        grep -v '^_scripts/' |
        grep -v '^bin/python/txt2tags-r900\.py' |
        grep -v '^blog/index\.html' |
        grep -v '^curso/index\.md' |
        grep -v '^feed\.xml' |
        grep -v '^index\.html' |
        grep -v '^tags/index\.html' |
        grep -v '^tela-preta/index\.md' |
        grep -v '^vim/vimrc-ivan\.txt' |

        # txt2tags files
        grep -v '^projects/config.t2t' |
        grep -v '^projects/emomemory/index.t2t' |
        grep -v '^shell/dialog/index' |
        grep -v '^[^:]*\.t2t:.*{{br}}' |
        cat -
    cd "$site_root"
}

check_missing_article_date() {
    # This check runs at the repo root
    # This is the default date inserted by the txt2tags2html script
    git grep '^date: 1999-12-31'
}

# Do not link URLs that are gone (410)
check_link_to_gone() {
    _scripts/list-urls-gone | while read url
    do
        # The last ? matches URLs missing the trailing slash
        cgrep -Ei "href=\"(https?://aurelio\.net)?$url?\"" $files
        cgrep -Ei  "src=\"(https?://aurelio\.net)?$url?\"" $files
    done
}

# Do not link URLs that are redirected (301)
check_link_to_redirected() {
    _scripts/list-urls-redirected |
    grep -Ev '^(/feed/|/blog/feed/)$' | # wontfix
    while read url
    do
        if echo "$url" | grep -Fq '*'
        then
            # Handle Netlify glob
            # Example: /img/icon16/*  /img/icon/16/:splat
            url=$(echo "$url" | sed 's/\*/[^"]*/g')
            cgrep -i "href=\"(https?://aurelio\.net)?$url\"" $files
            cgrep -i  "src=\"(https?://aurelio\.net)?$url\"" $files
        else
            # The last ? matches URLs missing the trailing slash
            cgrep -Ei "href=\"(https?://aurelio\.net)?$url?\"" $files
            cgrep -Ei  "src=\"(https?://aurelio\.net)?$url?\"" $files
        fi
    done
}

# Do not link foo/index.html, but foo/
check_link_to_index_html() {
    cgrep 'href="[^"]*/index\.html"' $files
}

# Do not use relative URLs in links and images
check_relative_urls() {
    # ./
    cgrep -i -E '(src|href)="\./' $files
    cgrep -i -E '(src|href)="[^"]*/\./' $files

    # ../
    cgrep -i -E '(src|href)="\.\./' $files
    cgrep -i -E '(src|href)="[^"]*/\.\./' $files
}

# No http:// for resources (mixed content) - #18
check_mixed_content() {
    cgrep -i -F 'src="http://aurelio.net' $files
    cgrep -i '<link [^>]*href="http://aurelio.net' $files
}

# Grep for <tag foo=bar> instead of <tag foo="bar">
check_unquoted_attributes() {
    echo "$files" |

        # Remove false positives
        grep -F -x -v '_site/bin/python/txt2tags-r900.py' |
        grep -F -x -v '_site/doc/coluna/coluna-09.html' |
        grep -F -x -v '_site/sed/programas/yahoogroups-kill-sig.sed' |
        grep -F -x -v '_site/vim/vimrc-ivan.txt' |

        # Check
        xargs grep -i -E '<[a-z]+ ([^>]* )?[a-z]+=[^\"]' |

        # Remove false positives
        grep -F -i -v 'content="text/html; charset=utf-8"' |
        #XXX txt2tags generated files, won't fix now
        grep -E -v '<HR NOSHADE SIZE=1>'
}

check_windows_linebreak() {
    echo "$files" |

        # Remove false positives
        grep -v '^_site/projects/moneylog/' |
        grep -v '^_site/moneylog/' |

        xargs file | grep CRLF
}

active_checks="
    check_accidental_liquid_markup
    check_missing_article_date
    check_link_to_gone
    check_link_to_redirected
    check_link_to_index_html
    check_windows_linebreak
    check_unquoted_attributes
    check_mixed_content
    check_relative_urls
"

for check in $active_checks
do
    echo "Running $check..."
    wrong=$($check)
    test -n "$wrong" && error "$wrong"
done
