#!/bin/bash
# Check for errors on the generated site

error() {
    echo "**** ERROR: $1"
    echo "$2" | head -n 40
    exit 1
}

# Make sure we are at the repository root
cd $(dirname "$0")
cd ..

relative_urls=$(
    # ./
    git grep -E '(src|href)="\./'
    git grep -E '(src|href)="[^"]*/\./'

    # ../
    git grep -E '(src|href)="\.\./'
    git grep -E '(src|href)="[^"]*/\.\./'
)

unquoted_attributes=$(
    # Grep for <tag foo=bar> instead of <tag foo="bar">
    git grep -E '<[a-z]+ [^>]*[a-z]=[^"]' |
        grep -F -v 'content="text/html; charset=utf-8"'
)

test -n "$relative_urls" && error "Do not use relative URLs" "$relative_urls"
test -n "$unquoted_attributes" && error "Unquoted HTML attributes" "$unquoted_attributes"


