#!/bin/bash
# Inform a URL (full with domain or root-relative) to grep.
#
# The script will always search for both full and root-relative when it's a
# URL from my own site, regardless of which type the user informed.
#
# Files are full matches and folders are partially matched in the text search
# (children will show up in the output). End it with /? if you want full match
# for a folder.
#
# Tip: you can use egrep regexes as URL, i.e. '.*\.svg'

# Make sure we are at the repository root
cd $(dirname "$0")
cd ..

domain='https?://aurelio\.net'
files=$(_scripts/list-site-files text)

check() {
    local user_url=$1

    # It's a full url from my site
    if echo "$user_url" | grep -E -q "^$domain"
    then
        full_url=$user_url
        root_relative_url=$(echo "$full_url" | sed -r "s/^$domain//")

    # It's an external url
    elif echo "$user_url" | grep -E -q '^https?://'
    then
        full_url=$user_url
        root_relative_url=

    # It's a root-relative url from my site
    else
        root_relative_url="/${user_url#/}"
        full_url="$domain$root_relative_url"
    fi

    # If $root_relative_url is set, it's a URL from my own site.
    # Then I always have to search with and without the domain prefix.
    #
    # Don't bother searching relative URLs, they will all be converted to
    # root-relative at some point (issue #20).
    #
    # Folders also have to be searched with and without the trailing slash.
    # FIXME remove this exception when issue #44 is fixed

    if test -n "$root_relative_url"
    then
        url="($domain)?$root_relative_url"
    else
        url=$full_url
    fi

    # Search HTML tags and URL-only (text files, etc)
    if echo "$url" | grep -q '/$'
    then
        # dir, dir/, dir/*
        regexes="(href|src)=\"${url%/}(/[^\"#]*)?[\"#]"
        regexes="$regexes|${full_url%/}(/|[^a-z0-9_-])"
    else
        # file
        regexes="(href|src)=\"$url[\"#]"
        regexes="$regexes|$full_url($|[^/a-z0-9_-])"
    fi

    # grep once all the regexes to make it faster
    grep --color=always -Ei "$regexes" $files
}

for this_url
do
    check "$this_url"
done
