#!/bin/bash
# Adapted from http://blog.endpoint.com/2010/04/tip-find-all-non-utf8-files.html
#
# Command to fix everything:
# _scripts/list-non-utf8-files | while read file; do echo $file; iconv -f iso-8859-1 -t utf-8 $file > foo; cat foo > $file; rm foo; done

# Make sure we are at the repository root
cd $(dirname "$0")
cd ..

_scripts/list-text-files |
  xargs -I {} bash -c "iconv -f utf-8 -t utf-16 {} &>/dev/null || echo {}"
