#!/bin/bash
# Adapted from http://blog.endpoint.com/2010/04/tip-find-all-non-utf8-files.html
#
# Command to fix everything:
# _scripts/list-non-utf8-files | while read file; do echo $file; iconv -f iso-8859-1 -t utf-8 $file > foo; cat foo > $file; rm foo; done

# Make sure we are at the repository root
cd $(dirname "$0")
cd ..

non_utf8=$(
    _scripts/list-repo-text-files |
        xargs -I {} bash -c "iconv -f utf-8 -t utf-16 {} &>/dev/null || echo {}"
)

if test -n "$non_utf8"
then
    echo "$non_utf8"
    exit 1
fi
