#!/bin/bash
# diff between remote and local file path for the aurelio.net website

set -eu

file="$1"
host="$REMOTE_USER@aurelio.net"
remote_root="~/aurelio.net"

cd $(dirname $0)/../../aurelio.net.html  # enter site root
diff -rNu <(ssh "$host" "cat $remote_root/$file") "$file" | vi -
