#!/bin/bash
# Wrapper to mdformat that preserves Jekyll's Front Matter

has_front_matter() {
    test '---' = "$(head -n 1 "$1")"
}

get_front_matter() {
    sed -n '/^---$/,/^---$/ p' "$1"
}

del_front_matter() {
    sed '/^---$/,/^---$/ d' "$1"
}

for file  # in $@
do
    if has_front_matter "$file"
    then
        # Format Markdown only, not Front Matter
        get_front_matter "$file"
        echo
        del_front_matter "$file" | mdformat -
    else
        cat "$file" | mdformat -
    fi 2>&1 |
        cat - > "$file.temp"
        mv "$file.temp" "$file"
        echo "Saved $file"
done
