#!/bin/bash
# Migrate txt2tags pages to plain HTML files.
# Also adds Jekyll front matter and tidy the markup.

# in/out
infile="$1"                       # foo.t2t
outfile="${infile%.t2t}.html"     # foo.html

# setup
site_root=$(pwd | sed 's@\(/aurelio.net/\).*@\1@')
txt2tags="$site_root/_scripts/txt2tags-2.6.1102"
tidy="$site_root/_scripts/html-tidy"
replace="$site_root/_scripts/replace"
replace_templates="$site_root/_scripts/replace-templates"

info() {
    echo
    echo "-------------------------- $*"
}

front_matter() {
    echo "---"
    echo "date: 1999-12-31"
    echo "title: $(get_txt2tags_title)"
    echo "---"
    echo
}

get_txt2tags_title() {
    # Join first two lines
    cat "$infile" | sed 2q | sed 'N;s/\n/ - /'
}

clean_infile() {
    cat "$infile" |
        # Remove theme header/footer/ads
        grep -v -E '^%!include: .*/(massa|10anos)/footer.t2t'
}

comments_warning() {
    local c n

    c=$(grep '^%[^!]' "$infile" | grep -v '^%%% *$')
    if test -n "$c"
    then
        info "WARNING: Hidden comments that will be lost:"
        echo "$c"
    fi

    n=$(grep -c '^%%% *$' "$infile")
    if test $n -gt 0
    then
        info "WARNING: There are $n block comments markers: %%%"
    fi
}

if ! test -f "$infile"
then
    echo "Input file not found: $infile"
    exit 1
fi

info "Convert to HTML"
front_matter > "$outfile"
clean_infile | "$txt2tags" -t html5 --no-headers --css-sugar -i - -o - >> "$outfile"
echo "Saved $outfile"

info "Tidy up"
"$tidy" "$outfile"

info "Fix images markup"

# Txt2tags files use <table> to align images with captions.
# Let's convert that to proper HTML tags and styling.

"$replace" --regex --in-place \
    --from-file "$replace_templates/txt2tags-image-caption-from.html" \
    --to-file   "$replace_templates/txt2tags-image-caption-to.html" \
    "$outfile"

"$replace" --regex --in-place \
    --from-file "$replace_templates/txt2tags-linked-image-caption-from.html" \
    --to-file   "$replace_templates/txt2tags-linked-image-caption-to.html" \
    "$outfile"

# Plain "solo" images in a paragraph

"$replace" --regex --in-place \
    --from-file "$replace_templates/txt2tags-image-solo-from.html" \
    --to-file   "$replace_templates/txt2tags-image-solo-to.html" \
    "$outfile"

info "Remove unused table styling"

"$replace" --in-place \
    --from '<table style="margin-left: auto; margin-right: auto;"' \
    --to   '<table' \
    "$outfile"

comments_warning
