#!/bin/bash

site_root=/a/www/surf
out=names.html

htmlize() {
	while read name; do
		first=${name:0:1}
		encoded_name=$(echo "$name" |
			sed -f /a/www/bin/sed/escape.sed)
		link="search.php?q=$encoded_name"
		if [ "$first" != "$previous_first" ]; then
			previous_first=$first
			name="<b>$first</b>${name:1:50}"
		fi
		echo "<a href=\"$link\">$name</a>"
		#echo "<a href=\"$link\">$name</a> . "
	done
}

# extract & sort all names, 1 per line
sed '
	/<br><br>[^<]/!d
	s/ *<[^>]*>//g
	/,/d
	/?/d
	/^Onda/d
	/^Parede/d
	/^Entubado$/d
	/^Ops!$/d
	/^:)/d
	/^&nbsp;/d' \
		$site_root/2006-??/??/[0-9]*.html \
		$site_root/200602*/html/* |
	sort -fdu |
	/a/bin/iso2txt |
	htmlize |
	sed '$ s/ . $//' > $out

echo $out saved	
