#!/bin/sh
# faz
# 20030312

IMG_PATT='<IMG ALI[^ ]* \(SRC="\([^"]*\)" [^>]*>\)'
IMG_RPLC='<a href=\"\2\"><img width=320 height=240 \1</a>'
txt2tags --stdout minhatoyota.t2t | sed "s
<IMG ALI[^ ]* \(SRC=\"\([^\"]*\)\" [^>]*>\)
<a href=\"\2\"><img width=320 height=240 \1</a>
" > minhatoyota.html

#sed "s|$IMG_PATT|<a href=\"\2\"><img width=320 height=240 \1</a>|" > minhatoyota.html

