#!/bin/bash

echo "Voce editou o _tagmenu*.js, ceto? Vou gerar o tagmenu-*.js"
read

[ -z "$1" -o "$1" == diet ] && {
	js-shrink _tagmenu-diet.js > tagmenu-diet.js
	echo feito tagmenu-diet.js
}
[ -z "$1" -o "$1" == urls -o "$1" == url ] && {
sed "s/^[[:blank:]]'/'/;s/'[[:blank:]]*: /':/;s/,[[:blank:]]*'/,'/g" _tagmenu-urls.js > tagmenu-urls.js
echo feito tagmenu-urls.js
}
